import { Router } from 'express';
import { authRouter } from './auth.routes.js';
import { leadsRouter } from './leads.routes.js';
import { googleRouter } from './google.routes.js';
import { settingsRouter } from './settings.routes.js';
import { packagesRouter } from './packages.routes.js';
import { studentsRouter } from './students.routes.js';
import { enrollmentsRouter } from './enrollments.routes.js';
import { adminRouter } from './admin.routes.js';
import { plannerRouter } from './planner.routes.js';
import { salaryRouter } from './salary.routes.js';
import { careerRouter } from './career.routes.js';
import { careerMissionsRouter } from './career-missions.routes.js';
import { missionCategoriesRouter } from './mission-categories.routes.js';
import { sopTemplatesRouter } from './sop-templates.routes.js';
import { sopStepsRouter } from './sop-steps.routes.js';
import { sopObservationsRouter } from './sop-observations.routes.js';
import { sopCategoriesRouter } from './sop-categories.routes.js';
import { sopSectionsRouter } from './sop-sections.routes.js';
import { sopRevisionsRouter } from './sop-revisions.routes.js';
import { teacherAppraisalsRouter } from './teacher-appraisals.routes.js';
import { allowanceRouter } from './allowance.routes.js';
import { financeRouter } from './finance.routes.js';
import { operatingCostRouter } from './operatingCost.routes.js';
import { uploadRouter } from './upload.routes.js';
import { candidatesRouter } from './candidates.routes.js';
import { attendanceRouter } from './attendance.routes.js';
import { speechRouter } from './speech.routes.js';
import { meRouter } from './me.routes.js';
import { authRolesRouter } from './auth-roles.routes.js';
import { pointsRouter } from './points.routes.js';
import { bugReportsRouter } from './bug-reports.routes.js';

export const router = Router();

router.get('/health', (_req, res) => {
  res.json({ status: 'ok' });
});

router.use('/auth', authRouter);
router.use('/leads', leadsRouter);
router.use('/google', googleRouter);
router.use('/settings', settingsRouter);
router.use('/packages', packagesRouter);
router.use('/students', studentsRouter);
router.use('/enrollments', enrollmentsRouter);
router.use('/admin', adminRouter);
router.use('/planner', plannerRouter);
router.use('/salary', salaryRouter);
router.use('/finance', financeRouter);
router.use('/operating-cost', operatingCostRouter);
router.use('/upload', uploadRouter);
router.use('/candidates', candidatesRouter);
router.use('/', careerRouter);
router.use('/', careerMissionsRouter);
router.use('/', missionCategoriesRouter);
router.use('/', sopTemplatesRouter);
router.use('/', sopStepsRouter);
router.use('/', sopObservationsRouter);
router.use('/', sopCategoriesRouter);
router.use('/', sopSectionsRouter);
router.use('/', sopRevisionsRouter);
router.use('/', teacherAppraisalsRouter);
router.use('/', allowanceRouter);
router.use('/', attendanceRouter);
router.use('/', speechRouter);
router.use('/', meRouter);
router.use('/', authRolesRouter);
router.use('/', pointsRouter);
router.use('/', bugReportsRouter);
