/**
 * Exports the current Teacher table as INSERT IGNORE SQL.
 * Run from the backend root:
 *   npx tsx scripts/export_teachers.ts > database/seed_teachers.sql
 *
 * It reads DATABASE_URL from .env automatically.
 */

import 'dotenv/config';
import mysql from 'mysql2/promise';

function esc(v: unknown): string {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'boolean') return v ? '1' : '0';
  if (typeof v === 'number') return String(v);
  if (v instanceof Date) return `'${v.toISOString().replace('T', ' ').replace('Z', '')}'`;
  // JSON / string
  const s = typeof v === 'object' ? JSON.stringify(v) : String(v);
  return `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

async function main() {
  const url = process.env.DATABASE_URL;
  if (!url) { console.error('DATABASE_URL not set'); process.exit(1); }

  const conn = await mysql.createConnection(url);
  const [rows] = await conn.execute('SELECT * FROM `Teacher` ORDER BY `createdAt`') as any[];
  await conn.end();

  if (!rows.length) { console.log('-- No teachers found'); return; }

  const cols = Object.keys(rows[0]);
  const colList = cols.map(c => `\`${c}\``).join(', ');

  const lines: string[] = [
    '-- Teacher seed — generated by scripts/export_teachers.ts',
    '-- Safe to run multiple times (INSERT IGNORE skips existing IDs)',
    '',
    `INSERT IGNORE INTO \`Teacher\` (${colList}) VALUES`,
  ];

  rows.forEach((row: any, i: number) => {
    const vals = cols.map(c => esc(row[c])).join(', ');
    const comma = i < rows.length - 1 ? ',' : ';';
    lines.push(`  (${vals})${comma}`);
  });

  console.log(lines.join('\n'));
}

main().catch(err => { console.error(err); process.exit(1); });
